defaults: &defaults
  docker:
      - image: debian:stretch

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
