defaults: &defaults
  docker:
    - image: debian:stretch

version: 2

workflows:
  version: 2
  deployment_pipeline:
    jobs:
      - build:
      - qa_build:

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: &hellow_world
          command: |
            echo "Hello World!"

  qa_build:
    <<: *defaults
    steps:
      - checkout 
      - run: 
          <<: *hello_world  
