defaults: &defaults
  docker:
    - image: debian:stretch

version: 2

jobs:
  build:
    environment: &environment_variables
      TERRAFORM_LOCATION: ./test1
      AFFECTED_FILES: /tmp/affected_files.txt
    <<: *defaults
    docker:
      - image: alpine/git
    steps:
      - checkout
      - run: &hello_world
          command: |
            echo "${TERRAFORM_LOCATION}"
      - run:
          command: |
            chmod +x /root/project/scripts/*
            ls -ltr /root/project/scripts/*

  deploy_qa:
    environment: 
      <<: *environment_variables
      TERRAFORM_LOCATION: ./test2
    <<: *defaults
    steps:
      - run:
         <<: *hello_world

workflows:
  version: 2
  deployment_pipeline:
    jobs:
      - build
      - advance_to_qa:
          requires:
            - build
          type: approval
          filters:
            branches:
              only:
                - master
      - deploy_qa:
          requires:
            - advance_to_qa
