defaults: &defaults
  docker:
    - image: debian:stretch

version: 2

jobs:
  build:
    environment: &environment_variables
      TERRAFORM_LOCATION: ./test1
      AFFECTED_FILES: /tmp/affected_files.txt
    <<: *defaults
    docker:
      - image: alpine/git
    steps:
      - checkout
      - run: &hello_world
          command: |
            echo "${TERRAFORM_LOCATION}"

  deploy_qa:
    environment: 
      <<: *environment_variables
      TERRAFORM_LOCATION: ./test2
    <<: *defaults
    steps:
      - run:
         <<: *hello_world
  
  rollback_code:
    environment:
      ROLLBACK_IMAGE: __IMAGE__
    <<: *defaults
    docker:
      - image: alpine/git
    steps:
      - checkout 
      - run:
          command: |
            ROLLBACK_IMAGE=$(awk -F'=' '{print $NF}' < /root/project/HelloWorld/rollback/rollback.cfg)
            docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
            docker pull chre268/helloworld:${ROLLBACK_IMAGE}
      
workflows:
  version: 2
  deployment_pipeline:
    jobs:
      - build
      - advance_to_qa:
          requires:
            - build
          type: approval
          filters:
            branches:
              only:
                - master
      - rollback:
          requires:
            - build
          type: approval
      - deploy_qa:
          requires:
            - advance_to_qa
      - rollback_code:
          requires: 
            - rollback
