defaults: &defaults
  docker:
    - image: debian:stretch
hellow_world: &hello_world
  | echo "Hello World"

version: 2

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: 
          command: *hello_world
