version: 2

jobs:
  build:
    steps:
      - checkout
      - run: &hello_world
          shell: /bin/sh
          command: |
            echo "Hello World!"
      - run:
          command: |
            echo "Hello World 2!"
      <<: *hello_world
