defaults: &defaults
  docker:
    - image: debian:stretch

version: 2

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: &hellow_world
          command: |
            echo "Hello World!"
