defaults: &defaults
  docker:
    - image: debian:stretch

version: 2

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: &hello_world
          command: |
            echo "Hello World!"
  deploy_qa:
    <<: *defaults
    steps:
      - run:
         <<: *hello_world

workflows:
  version: 2
  deployment_pipeline:
    jobs:
      - build:
         filters:
            branches:
              only:
                - master
      - advance_to_qa:
          requires:
            - build
          type: approval
          filters:
            branches:
              only:
                - master
       - deploy_qa
